src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>DD_Emergency_Provider__c</fullName>
        <label>Emergency Provider</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DD_First_Name__c</fullName>
        <label>First Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DD_GTF_Level__c</fullName>
        <label>GTF Level</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DD_Last_Name__c</fullName>
        <label>Last Name</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DD_Address__c.object
<CustomObject>
    <fields>
        <fullName>DD_Apartment_Number__c</fullName>
        <label>Apartment Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DD_City__c</fullName>
        <label>City</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DD_Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>DD_Provider__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>DEL_Provider_Addresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DD_State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>Alabama</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alaska</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arizona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arkansas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>California</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colorado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Connecticut</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delaware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>District of Columbia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Florida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Georgia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hawaii</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Idaho</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Illinois</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indiana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Iowa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kansas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kentucky</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Louisiana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maryland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Massachusetts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Michigan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Minnesota</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mississippi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missouri</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Montana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nebraska</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DD_Zip_Code__c</fullName>
        <label>Zip Code</label>
        <precision>9</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Street 1</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DD_Alternate_References__c.object
<CustomObject>
    <fields>
        <fullName>DD_Provider__c</fullName>
        <label>Provider</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Alternate Reference Numbers</relationshipLabel>
        <relationshipName>DEL_Alternate_References</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DD_Reference_Number__c</fullName>
        <label>Reference Number</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DD_Reference_Type__c</fullName>
        <label>Reference Type</label>
        <picklist>
            <picklistValues>
                <fullName>DFMS ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMAP Atypical Provider Id</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FSF TIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>I-SATS Id “MH”</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>I-SATS Id “SA”</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medicaid Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National Provider Id</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OIS Vendor Id</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OMS Department Code</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payee SSN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PBH Agency Code</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Alternate Reference</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Reference ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alternate References</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ProviderSearchController.cls
public with sharing class ProviderSearchController {

  private String soql {get;set;}
  
  public List<account> providers {get;set;}
    public account provider {get;set;}
    
  
  public String sortDir {
    get  { if (sortDir == null) {  sortDir = 'asc'; } return sortDir;  }
    set;
  }
  
  public String sortField {
    get  { if (sortField == null) {sortField = 'dd_Last_name__c'; } return sortField;  }
    set;
  }
  
  public String debugSoql {
    get { return soql + ' order by ' + sortField + ' ' + sortDir + ' limit 20'; }
    set;
  }
   
  public ProviderSearchController() {
    soql = label.ProviderSearchSOQL;
    runQuery();
  }
   
  public void toggleSort() {
   
    sortDir = sortDir.equals('asc') ? 'desc' : 'asc';
    
    runQuery();
  }
 
  public void runQuery() {

    try {
        system.debug('soql>>>'+soql);	
      providers = Database.query(soql + ' order by ' + sortField + ' ' + sortDir + ' limit 20');
        system.debug('Providers >>>'+providers);
    } catch (Exception e) {
      ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Ooops!'));
    }

  }
 
  public PageReference runSearch() {

    String firstName = Apexpages.currentPage().getParameters().get('firstname');
    String lastName = Apexpages.currentPage().getParameters().get('lastname');
    String street = Apexpages.currentPage().getParameters().get('street');
    String city = Apexpages.currentPage().getParameters().get('city');
    String emrPro = Apexpages.currentPage().getParameters().get('emrPro');
    String gtf = Apexpages.currentPage().getParameters().get('gtf');
    String refn = Apexpages.currentPage().getParameters().get('refn');
    String refType = Apexpages.currentPage().getParameters().get('refType');
    String state = Apexpages.currentPage().getParameters().get('state');
    String zip = Apexpages.currentPage().getParameters().get('zip');
    String apt = Apexpages.currentPage().getParameters().get('apt');
    String phone = Apexpages.currentPage().getParameters().get('phone');
    String parOrg = Apexpages.currentPage().getParameters().get('parOrg');
      
      
    if(!refn.equals('') ){
       soql =label.ProviderSearchSOQL+' and id in (select DD_Provider__c from dd_Alternate_References__c where dd_Provider__c != null';   
        if (!refn.equals(''))
          soql += ' and dd_Reference_Number__c LIKE \'%'+String.escapeSingleQuotes(refn)+'%\'';
        if (!refType.equals(''))
          soql +=  ' and dd_Reference_Type__c LIKE \'%'+String.escapeSingleQuotes(refType)+'%\'';  
        soql += ') ';
        system.debug('reference number SOQL'+soql);
      }
   
    
      if(!street.equals('') || !city.equals('')|| !state.equals('')|| !zip.equals('')|| !apt.equals('')|| !phone.equals('')){
       soql =label.ProviderSearchSOQL+' and id in (select dd_Provider__c from dd_Address__c where dd_Provider__c != null';
          if (!street.equals(''))
          soql += ' and Name LIKE \'%'+String.escapeSingleQuotes(street)+'%\'';
          if (!city.equals(''))
          soql +=  ' and dd_City__c LIKE \'%'+String.escapeSingleQuotes(city)+'%\''; 
          if (!state.equals(''))
          soql +=  ' and DD_State__c LIKE \'%'+String.escapeSingleQuotes(state)+'%\''; 
          if (!zip.equals(''))
          soql +=  ' and DD_Zip_Code__c ='+String.escapeSingleQuotes(zip); 
          if (!apt.equals(''))
          soql +=  ' and DD_Apartment_Number__c LIKE \'%'+String.escapeSingleQuotes(apt)+'%\''; 
          if (!phone.equals(''))
          soql +=  ' and DD_Phone__c LIKE \'%'+String.escapeSingleQuotes(phone)+'%\''; 
        soql += ') ';
      }
    
      else if(!firstName.equals('') || !lastName.equals('') || !emrPro.equals('') || !parOrg.equals('')){
        
        soql =label.ProviderSearchSOQL;
        if (!firstName.equals(''))
          soql += ' and dd_First_Name__c LIKE \'%'+String.escapeSingleQuotes(firstName)+'%\'';
        if (!lastName.equals(''))
          soql +=  ' and dd_Last_name__c LIKE \'%'+String.escapeSingleQuotes(lastName)+'%\'';
        if (!emrPro.equals(''))
          soql +=  ' and dd_Emergency_Provider__c LIKE \'%'+String.escapeSingleQuotes(emrPro)+'%\'';
        if (!gtf.equals(''))
          soql +=  ' and dd_GTF_Level__c LIKE \'%'+String.escapeSingleQuotes(gtf)+'%\'';
        if (!parOrg.equals(''))
          soql += ' and Parent LIKE \'%'+String.escapeSingleQuotes(parOrg)+'%\'';//Do it later
        
      }
   
   
    system.debug('SOQL >'+soql);
    runQuery();

    return null;
  }
    public  List<String> EmrgncyProVal
    { 
        get{
           List<string> options = new List<string>();
           Schema.DescribeFieldResult fieldResult = account.dd_Emergency_Provider__c.getDescribe();
           for( Schema.PicklistEntry f : fieldResult.getPicklistValues())
           {
              options.add(f.getLabel());
           }       
           return options;
        }
       set;
    } 
    public  List<String> gtfLvl
    { 
        get{
           List<string> options = new List<string>();
           Schema.DescribeFieldResult fieldResult = account.dd_GTF_Level__c.getDescribe();
           for( Schema.PicklistEntry f : fieldResult.getPicklistValues())
           {
              options.add(f.getLabel());
           }       
           return options;
        }
       set;
    } 
    public  List<String> refType
    { 
        get{
           List<string> options = new List<string>();
           Schema.DescribeFieldResult fieldResult = dd_Alternate_References__c.dd_Reference_Type__c.getDescribe();
           for( Schema.PicklistEntry f : fieldResult.getPicklistValues())
           {
              options.add(f.getLabel());
           }       
           return options;
        }
       set;
    } 
}