src/objects/DD_Service_Taxonomy__c.object
<CustomObject>
    <fields>
        <fullName>DD_Adoption_Status__c</fullName>
        <label>Adoption/FosterCare/Neither/Both</label>
        <picklist>
            <picklistValues>
                <fullName>Adoption</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster Care</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DD_Contract_Details__c</fullName>
        <label>Contracted/Non-Contracted/Both</label>
        <picklist>
            <picklistValues>
                <fullName>Contracted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Contracted</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DD_Conv_Residential_Status__c</fullName>
        <label>Conv-Residential/Nonresidential</label>
        <picklist>
            <picklistValues>
                <fullName>Residential</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Residential</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>DD_Conversion_Divisions__c</fullName>
        <label>Conversion Divisions</label>
        <picklist>
            <picklistValues>
                <fullName>All</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DFS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DFS+DMSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DFS+DMSS+DYRS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DFS+DPBHS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DFS+DPBHS+DYRS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DFS+DYRS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DPBHS: DPBHS+DYRS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DYRS</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>DD_Division__c</fullName>
        <label>Division</label>
        <picklist>
            <picklistValues>
                <fullName>DFS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DMSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DYRS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DPBHS</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>DD_Foster_Care_Setting_Type__c</fullName>
        <label>Foster Care Setting Type</label>
        <picklist>
            <picklistValues>
                <fullName>Foster Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Juvenile Justice</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medical Hospital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DD_Health_Procedure_Codes__c</fullName>
        <label>Health Procedure Codes</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DD_Level_1_Code__c</fullName>
        <label>Level 1 Code</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DD_Level_1__c</fullName>
        <label>Level 1 : Description</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DD_Level_2_Code__c</fullName>
        <label>Level 2 Code</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DD_Level_2__c</fullName>
        <label>Level 2 : Services</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DD_Level_3_Code__c</fullName>
        <label>Level 3 Code</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DD_Level_3__c</fullName>
        <label>Level 3 : SubServices</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DD_MA_Service__c</fullName>
        <label>MA Fee for Service</label>
        <picklist>
            <picklistValues>
                <fullName>Fee For Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bundled</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DD_Paid_Status__c</fullName>
        <label>Paid/Non-Paid/Both</label>
        <picklist>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-paid</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DD_Reimbursable_Payment__c</fullName>
        <label>IV-E Reimbursable Payment</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DD_Residential_Status__c</fullName>
        <label>Residential/Nonresidential</label>
        <picklist>
            <picklistValues>
                <fullName>Residential</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Residential</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>DD_Service_Status__c</fullName>
        <label>Service Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Service Taxonomy</label>
    <nameField>
        <displayFormat>ST-{00000}</displayFormat>
        <label>Service Taxonomy Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Taxonomy</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TaxonomySearchCtrl.cls
public class TaxonomySearchCtrl{

    public List<DD_Service_Taxonomy__c> serviceTaxonomies {get;set;}
    public String ProviderId {get;set;}
    public String searchQuery{get;set;}
    public String selectedDivision { get;set;}
    public String Level1Code {get;set;}
    public String Level2Code {get;set;}
    public String Level3Code {get;set;}    
    public String Level1Desc {get;set;}
    public String Level2Serv {get;set;}
    public String Level3SubServ {get;set;}
    public String HPC {get;set;}
    public String Resident {get;set;}
    public String serviceStat {get;set;}
    public String ShowResults{get;set;}

    public TaxonomySearchCtrl(){
        serviceTaxonomies = new List<DD_Service_Taxonomy__c>();
        ProviderId = ApexPages.currentPage().getParameters().get('providerId');
        ShowResults = '';
    }

    public List<SelectOption> getDivisions(){
        List<SelectOption> options = new List<SelectOption>();        
        Schema.DescribeFieldResult fieldResult = DD_Service_Taxonomy__c.DD_Division__c.getDescribe();
        options.add(new SelectOption('None', '--None--'));       
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();        
        for( Schema.PicklistEntry f : ple){
          options.add(new SelectOption(f.getLabel(), f.getValue()));
        }       
       return options;
    }

    public List<SelectOption> getStatus(){
        List<SelectOption> options = new List<SelectOption>();        
        Schema.DescribeFieldResult fieldResult = DD_Service_Taxonomy__c.DD_Service_Status__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues(); 
        options.add(new SelectOption('None', '--None--'));       
        for( Schema.PicklistEntry f : ple){
          options.add(new SelectOption(f.getLabel(), f.getValue()));
        }       
       return options;
    }

    public List<SelectOption> getResidential(){
        List<SelectOption> options = new List<SelectOption>(); 
        options.add(new SelectOption('None', '--None--'));              
        Schema.DescribeFieldResult fieldResult = DD_Service_Taxonomy__c.DD_Residential_Status__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();        
        for( Schema.PicklistEntry f : ple){
          options.add(new SelectOption(f.getLabel(), f.getValue()));
        }       
       return options;
    }
        
    public PageReference getMatchingRecords(){         
         system.debug('\n\n Level1Code - ' + Level1Code + '\n\n Level2Code - ' + Level2Code + '\n\n Level3Code - '+ Level3Code + 
                 '\n\n Level1Desc -' + Level1Desc + '\n\n Level2Serv - ' + Level2Serv + '\n\n Level3SubServ - '+ Level3SubServ);
        system.debug('\n\n HPC - ' + HPC + '\n\n Resident - ' + Resident + '\n\n serviceStat - '+ serviceStat + 
                 '\n\n selectedDivision -' + selectedDivision);                 
         
         searchQuery               = 'SELECT id, DD_Adoption_Status__c, DD_Contract_Details__c, DD_Conversion_Divisions__c, DD_Conv_Residential_Status__c, '+
                                            ' DD_Division__c, DD_Foster_Care_Setting_Type__c, DD_Health_Procedure_Codes__c, DD_Reimbursable_Payment__c, DD_Level_1__c, '+
                                            ' DD_Level_1_Code__c, DD_Level_2__c, DD_Level_2_Code__c, DD_Level_3__c, DD_Level_3_Code__c, DD_MA_Service__c, '+
                                            ' DD_Paid_Status__c, DD_Residential_Status__c, DD_Service_Status__c '+
                                      ' FROM DD_Service_Taxonomy__c ' ;
        if((!String.isEmpty(Level1Code) && !Level1Code.isNumeric()) || (!String.isEmpty(Level2Code) && !Level2Code.isNumeric()) || (!String.isEmpty(Level3Code) && !Level3Code.isNumeric())){
            ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.Error, Label.OnlyNumeric);
            ApexPages.addMessage(msg);
            return null;
        }
                              
        if(!String.isEmpty(Level1Code) || !String.isEmpty(Level2Code) || !String.isEmpty(Level3Code) || !String.isEmpty(Level1Desc) 
                || !String.isEmpty(Level2Serv) || !String.isEmpty(Level3SubServ) || !String.isEmpty(HPC) 
                || (!String.isEmpty(selectedDivision) && selectedDivision != 'None') || (!String.isEmpty(Resident) && Resident != 'None') || (!String.isEmpty(serviceStat) && serviceStat != 'None')){
            searchQuery = searchQuery + ' WHERE ';
        } 
        if(!String.isEmpty(Level1Code)){
            searchQuery = searchQuery + ' DD_Level_1_Code__c = '+ Integer.valueOF(Level1Code) +' AND ';
        }
        if(!String.isEmpty(Level2Code)){
            searchQuery = searchQuery + ' DD_Level_2_Code__c = '+ Integer.valueOF(Level2Code) +' AND ';
        }
        if(!String.isEmpty(Level3Code)){
            searchQuery = searchQuery + ' DD_Level_3_Code__c = '+ Integer.valueOF(Level3Code) +' AND ';
        }
        if(!String.isEmpty(Level1Desc)){
            searchQuery = searchQuery + ' DD_Level_1__c = \''+ Level1Desc +'\' AND ';
        }
        if(!String.isEmpty(Level2Serv)){
            searchQuery = searchQuery + ' DD_Level_2__c = \''+ Level2Serv +'\' AND ';
        }
        if(!String.isEmpty(Level3SubServ)){
            searchQuery = searchQuery + ' DD_Level_3__c = \''+ Level3SubServ +'\' AND ';
        }

        if(!String.isEmpty(Level3SubServ)){
            searchQuery = searchQuery + ' DD_Level_3__c = \''+ Level3SubServ +'\' AND ';
        }

        if(!String.isEmpty(HPC)){
            searchQuery = searchQuery + ' DD_Health_Procedure_Codes__c = \''+ HPC +'\' AND ';
        }

        if(!String.isEmpty(selectedDivision) && selectedDivision != 'None'){
            searchQuery = searchQuery + ' DD_Division__c INCLUDES ' + formatForList(selectedDivision) + ' AND ';
        }

        if(!String.isEmpty(Resident) && Resident != 'None'){
            searchQuery = searchQuery + ' DD_Residential_Status__c = \''+ Resident +'\' AND ';
        }

        if(!String.isEmpty(serviceStat) && serviceStat != 'None'){
            searchQuery = searchQuery + ' DD_Service_Status__c =\''+ serviceStat +'\' AND ';
        }
        
        if(searchQuery.endsWith('AND ')){
            searchQuery = searchQuery.substring(0, searchQuery.length() - 4);
        }

        system.debug('\n searchQuery: ' + searchQuery);
        serviceTaxonomies = Database.Query(searchQuery);
        if(serviceTaxonomies.Size() > 0){
            ShowResults = 'Yes';
        }else{
            ShowResults = 'No';
        }
        system.debug('\n\n ShowResults : ' + ShowResults );
        return null;
    }

    public string formatForList (List<string> qList){
        string qCond = '(';
        for(string str : qList){
            str = string.escapeSingleQuotes(str);
            qCond = qCond + '\''+str +'\',';
        }
        qCond = qCond.substring(0,qCond.length() - 1) + ')';
        
        return qCond;       
    }

    public string formatForList (string field){
        List<string> tempList = new List<string>();
        tempList.add(field);
        return formatForList(tempList);       
    }

    public PageReference createNew(){
        Schema.DescribeSObjectResult r = DD_Service_Taxonomy__c.sObjectType.getDescribe();
        String keyPrefix = r.getKeyPrefix();
        system.debug('\n keyPrefix - ' + keyPrefix);
        PageReference pr = new PageReference('/'+ keyPrefix + '/e');
        pr.setRedirect(true);
        return pr;
    }
}